### ISSUE TITLE
Is possible to use this to download photos (.jpg or .png) and save in disk?

### ISSUE THREAD

**Issue by fnando1995** [zubkovyuriy/videowall#1]
Is possible to use this to download photos (.jpg or .png) and save in disk? Is so, can you please add it.

**Comment by yuriizubkov** [comment]
@fnando1995 Technically I think this is possible. Unfortunately I have no time right now to add this functionality. I leave this issue opened, maybe I (or somebody else) will add this feature later.

**Comment by fnando1995** [comment]
Oka! Thanks!
